services:
  - type: web
    name: atelier-zacatecas-saas
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Atelier Zacatecas
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://atelier_db_55go_user:ihntg9j5zelCTy2VF6ltL61GZ9qN8VxW@dpg-dai4776k1f9s73bu75fg-a/atelier_db_55go
      - key: DB_CONNECTION
        value: central
      - key: CENTRAL_DB_CONNECTION
        value: central
      - key: SESSION_CONNECTION
        value: central
      - key: DB_CACHE_CONNECTION
        value: central
      - key: DB_QUEUE_CONNECTION
        value: central
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://atelier-zacatecas.onrender.com/auth/google/callback
